### ISSUE TITLE
Internal server error when storing two taxonomies with same name

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/database-layer#267]
# What is wrong?
`TaxonomyTermCreate`, when creating new taxonomy with same name as another taxonomy in same instance, throws a database constraint error, that is not handled and leads to a internal server error.
# Steps to reproduce
run `yarn fetch TaxonomyTermCreateMutation '{"parentId": 1328, "name": "repeteme", "taxonomyType": "topic-folder", "userId": 1}'` twice
# How should it behave?
It should respond with a friendly and descriptive error message, something like `two taxonomy terms cannot have same name in same instance` (done).
It should also ignore taxonomy terms that were already trashed.
Maybe better would be to not have at all this constraint and be able to store taxonomies with repeated name.
Or even better: 1. not have the constraint, 2. DB layer assures that the parent doesn't have children with repeated names

**Comment by kulla** [comment]
> Or even better: 1. not have the constraint, 2. DB layer assures that the parent doesn't have children with repeated names

Yep, that would be the best solution :smile: This is an old problem we have with the taxonomy from legacy serlo.org

**Comment by hugotiburtino** [comment]
- [ ] Remove the constraint from dump
- [ ] Remove the contraint from staging and prod
- [ ] Implement logic in TaxonomyTerm.create: 
  - [ ]  get all children names from parent and compare if name is equal to the new taxonomy
  - [ ]  trim empty spaces, check case "insensitvely"
  - [ ]  If content is different, pass. If same, throw a error with friendly message. like `parent with id {} has already another child with name {}`
