### ISSUE TITLE
[New Endpoint] EntityCopyMutation

### ISSUE THREAD

**Issue by MoeHome** [serlo/database-layer#292]
### Message (TypeScript definition)

```ts
interface Message {
  type: 'EntityCopyEntityMutation'
  payload: Payload
}

interface Payload {
  entityId: number!,
  userId: number!
}
```

### Output (TypeScript definition)

```ts
interface Output {
  entityId: number!
}
```

## Description what happens in the database layer
Creates a new entity with the same properties as the given entity. Also copies possible children.

## Necessary checks / possible errors

- [ ] Only entities which don't have a parent entity are allowed to be copied.
- [ ] Set entity_links for possible children.

**Comment by elbotho** [comment]
(What would this be used for?)

**Comment by MoeHome** [comment]
It's a user wish in backlog. There are two use cases. 1. User wants to create a new Entity with similar structure/content. 2. User wants to translate a page.
