### ISSUE TITLE
Upgrade sqlx to the most recent version

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/database-layer#343]
# What could be better?
Upgrade the core lib sqlx to newest version.

# Reasons for refactoring

- Avoid bigger breaking changes in the future
- Better support of MySQL specificities

# How could it be?
`sqlx = { version = "0.6.2", ... ` or newer

# What could go wrong? 
Unfortunatelly sqlx does not follow semver, it means there are already breaking changes in this upgrade. Luckly, Rust compiler helps us in this task.

**Comment by AndreasHuber** [comment]
sqlx upgrade included in https://github.com/serlo/database-layer/pull/464
