### ISSUE TITLE
Allow entity type Event to be linked to a topic folder

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/database-layer#359]
# What is wrong?
Entities of type event cannot be linked to topic folders, although there are already some like it (see https://de.serlo.org/community/146491/templates-f%C3%BCr-veranstaltungen)
```graphql
{
  uuid(id:146491) {
    ... on TaxonomyTerm {
      type
      children {
        nodes {
          id
          __typename
        }
      }
    }
  }
}
{
  "data": {
    "uuid": {
      "type": "exerciseFolder",
      "children": {
        "nodes": [
          {
            "id": 145455,
            "__typename": "Event"
          },
          {
            "id": 145459,
            "__typename": "Event"
          },
          {
            "id": 145464,
            "__typename": "Event"
          },
          {
            "id": 145458,
            "__typename": "Event"
          },
          {
            "id": 147733,
            "__typename": "Event"
          }
        ]
      }
    }
  }
}
```

# Steps to reproduce
Try to link 259562 to 146491 and you are going to receive "entity with id 259562 cannot be linked to a topic folder", which occurs [here](https://github.com/serlo/database-layer/blob/f00b1d5f0386e7471eb958c08c98d3b383e2132b/server/src/uuid/model/taxonomy_term/mod.rs#L584)

# How should it behave?
You link an entity event to a topic folder and receives Ok response.

# Discussions
@elbotho @kulla 
It there any reason why we should not allow it? Is it because we just want exercises in a topic folder?
Is 146491 something we don't want to support in the long term? Should we rather make it a topic?

_Reported by Anne_

**Comment by kulla** [comment]
See https://serlo.slack.com/archives/C0BMSC431/p1674472609379739?thread_ts=1674228167.231119&cid=C0BMSC431 -> its a feature not a bug.
