### ISSUE TITLE
Optimize SQL statement for EntityMetadataQuery

### ISSUE THREAD

**Issue by kulla** [serlo/database-layer#404]

**Comment by AndreasHuber** [comment]
My pull request only provided the benchmarking to verify if optimization is successful but no optimization at all. Therefore, it should not have closed the ticket.

**Comment by AndreasHuber** [comment]
Apparently the benchmarking shows that the performance is not as catastrophic as feared. Since no immediate idea for improvement - with the old MySQL version at least - comes up, we so close this for now.
