### ISSUE TITLE
Implement that entities with empty description (`description === ""`) do not return a description

### ISSUE THREAD

**Issue by kulla** [serlo/database-layer#406]

**Comment by hugotiburtino** [comment]
According to https://dini-ag-kim.github.io/amb/draft/#description it is not required, so the field should not appear.
But if it is there, it should be a string and, according to this [forum](https://groups.google.com/g/json-schema/c/J6QPptNBJgI)

> JSON Schema does not allow null as a value unless it is specifically allowed.  In your first example schema, a null value would not be valid.

What means the current behavior, returning `"description": null` is not valid.
