### ISSUE TITLE
Metadata API: remove `headline` field when empty

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/database-layer#411]
Currently we use headline field, but I can't find it in the AMB specification. I suppose it was in a previous version of it.
In that case, we could just remove it.

**Comment by kulla** [comment]
Nah, `headline` is fine. Keep in mind that we export `schema.org` so it's fine to have additional properties and here we export https://schema.org/headline -> @MoeHome Please make sure that this field is not present when there is no title
