### ISSUE TITLE
Pacts workflow (pacts_test job) is broken 

### ISSUE THREAD

**Issue by eliflores** [serlo/database-layer#458]
## What is wrong?

The [Pacts](https://github.com/serlo/database-layer/actions/workflows/pacts.yml) workflow is broken 💔 
The [pacts_test](https://github.com/serlo/database-layer/blob/main/.github/workflows/pacts.yml#L5) job fails with the following:

```
Failures:

1) Verifying a pact between api.serlo.org and serlo.org-database-layer - Message EntityCheckoutRevisionMutation with payload {"revisionId":30674,"userId":1,"reason":""} (case 200-response)
    1.1) has status code 200
           expected 200 but was 400
2) Verifying a pact between api.serlo.org and serlo.org-database-layer - Message EntityRejectRevisionMutation with payload {"revisionId":30674,"userId":1,"reason":""} (case 200-response)
    2.1) has status code 200
           expected 200 but was 400
3) Verifying a pact between api.serlo.org and serlo.org-database-layer - Message PageCheckoutRevisionMutation with payload {"revisionId":35476,"userId":1,"reason":""} (case 200-response)
    3.1) has status code 200
           expected 200 but was 400
4) Verifying a pact between api.serlo.org and serlo.org-database-layer - Message PageRejectRevisionMutation with payload {"revisionId":35476,"userId":1,"reason":""} (case 200-response)
    4.1) has status code 200
           expected 200 but was 400

There were 4 pact failures

FAIL __tests-pacts__/pacts.js (33.68 s)
  ✕ Pacts (32384 ms)
```

[This](https://github.com/serlo/database-layer/actions/runs/5333556734/jobs/9664174962?pr=457) is an example of a failed job.

## Steps to reproduce

Open a PR in the [database-layer](https://github.com/serlo/database-layer) repository. 
The `Pacts / pacts_test (pull_request)` check will fail.

## How should it behave?

The [Pacts](https://github.com/serlo/database-layer/actions/workflows/pacts.yml) workflow should run with no errors ✅
The `Pacts / pacts_test (pull_request)` check should pass for open PRs. 

## Notes 
The same error happens for the [Pact Broker](https://github.com/serlo/database-layer/actions/runs/5326969402/workflow) workflow, that runs after merging a PR to `main`. Example [here](https://github.com/serlo/database-layer/actions/runs/5326969402/jobs/9649725357).

**Comment by kulla** [comment]
See https://github.com/serlo/database-layer#run-contract-tests how to test them when somebody wants to solve it

**Comment by eliflores** [comment]
**Note**: This is a duplicate of https://github.com/serlo/api.serlo.org/issues/911
